beta: 0.5
embed_model: "dinov2_vits14"
test_size: 0.1
image_size: 560
model: 'MLPClassifier'
model_params:
    hidden_layer_sizes: [(50,50,50), (50,100,50), (100,)]
    activation: ['tanh', 'relu']
    alpha: [0.0001, 0.001, 0.01, 0.1]
    learning_rate: ['constant','adaptive']
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "RandomizedSearchCV"
cv_params:
   cv: 5
   n_iter: 50
   refit: 'ap_50'
   verbose: 1
   n_jobs: -1