project: "GIGAv1"
beta: 0.5
embed_model: "dinov2_vitl14"
test_size: 0.2
image_size: 560
model: 'LogisticRegression'
model_params:
    penalty: ['l1', 'l2']
    C: [0.001, 0.01, 0.1, 1.0, 10]
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "GridSearchCV"
cv_params:
   cv: 5
   refit: 'fbeta_score_0.5'
   verbose: 1
   n_jobs: -1