embed_model: "esa_foundation_v2"
project: "GIGAv1"
beta: 0.5

input_dim: 3
depths: [2, 2, 3, 3, 4, 4]
dims: [16, 16, 32, 32, 64, 64]
latent_dim: 1024
dropout: [0.85, 0.85, 0.90, 0.90, 0.95, 0.95]

test_size: 0.2
image_size: 256
model: 'LogisticRegression'
model_params:
    penalty: ['l1', 'l2']
    C: [0.001, 0.01, 0.1, 1.0, 10]
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "GridSearchCV"
cv_params:
   cv: 5
   refit: 'fbeta_score_0.5'
   verbose: 1
   n_jobs: -1