vectors_dir: 'data/vectors/'
rasters_dir: 'data/rasters/'
iso_codes: ['SEN']

proximity: 300
filter_buffer_size: 150
sample_spacing: 300
object_proximity: 300
priority: ["UNICEF", "OSM", "OVERTURE"]

