vectors_dir: 'data/vectors/'
rasters_dir: 'data/rasters/'
iso_codes: ['KEN']

proximity: 50
filter_buffer_size: 150
sample_spacing: 300
object_proximity: 300
name_match_threshold: 85
name_match_proximity: 300
priority: ["OSM", "OVERTURE", "UNICEF"]

