project: "GIGAv3"
vectors_dir: 'data/vectors/'
rasters_dir: 'data/rasters/'
iso_codes: ["GHA"]

proximity: 50
filter_buffer_size: 150
sample_spacing: 300
object_proximity: 300
priority: ["OSM", "OVERTURE"]