project: "GIGAv2"
scorer: "pr_auc"
test_size: 0.10
batch_size: 32
n_workers: 4
n_epochs: 60
beta: 0.5

model: "convnext_large"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
label_smoothing: 0.1
lr: 0.0001
img_size: 224
momentum: 
gamma: 
step_size: 
patience: 5
dropout: 