project: "GIGAv3"
scorer: "ap"
test_size: 0.10
batch_size: 32
n_workers: 4
n_epochs: 60
beta: 0.5

model: "xception"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
label_smoothing: 0.1
lr: 0.00001
img_size: 224
patience: 7
dropout: 
momentum: 
gamma: 
step_size: 