beta: 0.5
test_size: 0.1
batch_size: 32
n_workers: 4
n_epochs: 60
scorer: "p_auprc"

model: "xception"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
label_smoothing: 0.1
lr: 0.0001
img_size: 224
patience: 7
dropout: 
momentum: 
gamma: 
step_size: 
lr_min: 0.0000001
normalize: "imagenet"