digitalglobe_url: "https://evwhs.digitalglobe.com/mapservice/wmsaccess?"
size: 150
width: 500
height: 500
srs: 'EPSG:4326'
styles: ''
transparent: True
request: 'GetMap'
format: 'image/geotiff'
layers: ['DigitalGlobe:Imagery']
exceptions: 'application/vnd.ogc.se_xml'
featureprofile: 'Most_Aesthetic_Mosaic_Profile'
coverage_cql_filter: 'productType =%27Pan Sharpened Natural Color%27'
coverage_cql_filter: ''